### ISSUE TITLE
Failed to activate the linter-php package

### ISSUE THREAD

**Issue by gwinn** [AtomLinter/linter-php#104]
[Enter steps to reproduce below:]

When open any php file i've got this error message

**Atom Version**: 1.2.3
**System**: "Fedora release
**Thrown From**: [linter-php](https://github.com/AtomLinter/linter-php) package, v1.1.3

### Stack Trace

Failed to activate the linter-php package

```
At require(...)(...)[1].getFileName is not a function

TypeError: require(...)(...)[1].getFileName is not a function
    at Object.install (/home/gwinn/.local/share/atom/packages/linter-php/node_modules/atom-package-deps/lib/main.js:15:47)
    at Object.module.exports.activate (/home/gwinn/.local/share/atom/packages/linter-php/lib/main.coffee:26:34)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:170:19)
    at /usr/share/atom/resources/app.asar/src/package.js:784:28
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at PackageManager.module.exports.PackageManager.triggerActivationHook (/usr/share/atom/resources/app.asar/src/package-manager.js:528:41)
    at TokenizedBuffer.module.exports.TokenizedBuffer.setGrammar (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:181:27)
    at TokenizedBuffer.module.exports.TokenizedBuffer.reloadGrammar (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:192:21)
    at new TokenizedBuffer (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:78:12)
    at new DisplayBuffer (/usr/share/atom/resources/app.asar/src/display-buffer.js:85:32)
```

### Commands

```
  6x -0:18.7.0 click (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "projectHome": "/home/gwinn/Sources"
  }
}
```

### Installed Packages

```coffee
# User
linter, v1.11.2
linter-php, v1.1.3
linter-phpcs, v1.3.0
linter-phpmd, v1.3.2
php-extract-method, v0.2.0
php-twig, v4.0.0

# Dev
No dev packages
```

**Comment by hultberg** [comment]
After upgrading my linter-php package I'm getting the same error on every php file I open. Using atom 1.2.3.

**Comment by zakir-hyder** [comment]
i am facing the same issue

**Comment by steelbrain** [comment]
Fixed by https://github.com/steelbrain/package-deps/pull/31

Here's what you can do to make it work on your installation
```
cd ~/.atom/packages/linter-php
rm -rf node_modules/atom-package-deps
npm install atom-package-deps@latest
```

**Comment by zakir-hyder** [comment]
Thanks @steelbrain

**Comment by gwinn** [comment]
Thanks @steelbrain

**Comment by hultberg** [comment]
Thank you @steelbrain :smile:

**Comment by rustanacexd** [comment]
Thanks @steelbrain

**Comment by adi518** [comment]
Hmm, @steelbrain I did what you suggested, but I'm still getting an error: "Cannot find module 'atom-linter'".

**Comment by steelbrain** [comment]
@adi518 You should have the module if you have executed the commands I mentioned above, do you get any error executing the last one?

**Comment by adi518** [comment]
No errors, it installs fine. I have an `atom-linter` folder inside of `/linter-php` so it's odd that it isn't working.

**Comment by Arcanemagus** [comment]
@adi518 Have you tried uninstalling and re-installing the whole package?
