### ISSUE TITLE
Not working...

### ISSUE THREAD

**Issue by swblankenship** [AtomLinter/linter-php#123]
I've having difficulties trying to get linter-php working.  

1. I've installed/uninstalled, 
2. Changed the php path to /usr/bin/php, 
3. Have linter installed and enabled.  
4. I'm also able to get [linter-phpcs](https://atom.io/packages/linter-phpcs) working.  

I'm running Atom 1.4.1 on Mac 10.10.5
 
## apm test results

When I run `apm test` within the `.atom/packages/linter-php` directory, I get the following.  I'm not sure what this is trying to tell me. Any ideas?

```
[6719:0128/160006:ERROR:renderer_main.cc(200)] Running without renderer sandbox
[6715:0128/160008:INFO:CONSOLE(52)] "Window load time: 1614ms", source: file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js (52)
.FF[6715:0128/160008:INFO:CONSOLE(46)] "Uncaught (in promise) TypeError: Cannot read property 'type' of undefined", source: /Users/swblank10/.atom/packages/linter-php/spec/linter-php-spec.js (46)
F..

The php -l provider for Linter
  checks bad.php and
    it finds at least one message
      Expected 0 to equal 1.
        Error: Expected 0 to equal 1.
        at /Users/swblank10/.atom/packages/linter-php/spec/linter-php-spec.js:38:35
        at process._tickCallback (node.js:368:9)
    it verifies that message
      Expected promise to be resolved, but it was rejected with: Cannot read property 'type' of undefined {  }
  it should be an active package
    Expected false to be true.
      at [object Object].<anonymous> (/Users/swblank10/.atom/packages/linter-php/spec/linter-php-spec.js:22:64)
      at process._tickCallback (node.js:368:9)


Finished in 0.871 seconds
6 tests, 6 assertions, 3 failures, 0 skipped

Tests failed
```

**Comment by Arcanemagus** [comment]
Looks like I forgot to release a version supporting the latest `php` (which also includes fixed specs), hold on...

**Comment by Arcanemagus** [comment]
Try v1.1.7 and see if it fixes it for you.

**Comment by swblankenship** [comment]
Thanks for the quick reply.  This is what I'm getting now with v1.1.7:

```
[7867:0128/164844:ERROR:renderer_main.cc(200)] Running without renderer sandbox
[7863:0128/164845:INFO:CONSOLE(52)] "Window load time: 628ms", source: file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js (52)
bash: no job control in this shell
...F..

The php -l provider for Linter
  checks bad.php and
    it verifies that message
      Expected 'parse error' to equal 'syntax error, unexpected '{''.
        Error: Expected 'parse error' to equal 'syntax error, unexpected '{''.
        at /Users/swblank10/.atom/packages/linter-php/spec/linter-php-spec.js:49:36
        at process._tickCallback (node.js:368:9)


Finished in 1.974 seconds
6 tests, 14 assertions, 1 failure, 0 skipped
```

**Comment by Arcanemagus** [comment]
So that's what I've been running into on https://github.com/AtomLinter/linter-php/pull/121 and haven't had a OS X user able to help test :stuck_out_tongue:

Are you on Atom's Slack?

**Comment by swblankenship** [comment]
I'd be happy to help.  I just joined, at swblankenship

**Comment by Arcanemagus** [comment]
Whoops, this ended up being a configuration issue, worked out in private chat.
