### ISSUE TITLE
--syntax check is not a known command

### ISSUE THREAD

**Issue by t-prod** [AtomLinter/linter-php#151]
Hello,

I have this error when I open a PHP file in Atom :

```
Error: '"--syntax-check"' is not recognized as an internal control
or external, an executable program or batch file.
    at parameters.exit (C:\Users\Cyril\.atom\packages\linter-php\node_modules\atom-linter\lib\helpers.js:47:27)
    at triggerExitCallback (C:\Users\Cyril\AppData\Local\atom\app-1.6.2\resources\app.asar\src\buffered-process.js:213:47)
    at C:\Users\Cyril\AppData\Local\atom\app-1.6.2\resources\app.asar\src\buffered-process.js:227:18
    at Socket.<anonymous> (C:\Users\Cyril\AppData\Local\atom\app-1.6.2\resources\app.asar\src\buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

Anything to install ?

Regards

**Comment by Arcanemagus** [comment]
What does the `linter-php` section of your `config.cson` look like? The only thing I can think is that you put a ` ` into the Executable path setting (thus making it no longer use the default of `php`).

**Comment by t-prod** [comment]
Hi,

```
  "linter-php":
    executablePath: "C:\\Users\\Cyril\\OneDrive\\sites\\dev\\bin\\php\\php-7.0.3\\php.exe"
```

I try without tht php.exe but it remains the same.

**Comment by Arcanemagus** [comment]
If you open Atom's Developer Tools and place a breakpoint [here](https://github.com/AtomLinter/linter-php/blob/v1.2.0/lib/main.coffee#L51) what do `command` and `parameters` contain?

**Comment by Arcanemagus** [comment]
Marking as closed due to lack of response, if you are still having issues please run the debugging step above and report back :wink:.
