### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by jeffdupont** [AtomLinter/linter-php#16]
installed version 0.193.0

**Atom Version**: 0.193.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-php](https://github.com/AtomLinter/linter-php) package, v0.0.12

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/dupont/Dropbox/Application Data/atom/packages/linter-php/lib/linter-php.coffee:29

TypeError: undefined is not a function
  at LinterPhp.destroy (/Users/dupont/Dropbox/Application Data/atom/packages/linter-php/lib/linter-php.coffee:29:17)
  at LinterView.remove (/Users/dupont/Dropbox/Application Data/atom/packages/linter/lib/linter-view.coffee:252:7)
  at /Users/dupont/Dropbox/Application Data/atom/packages/linter/lib/linter-view.coffee:124:8
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.destroyed (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:279:27)
  at TextEditor.module.exports.Model.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/model.js:45:58)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:444:18)
  at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:419:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:582:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:621:21)
  at atom-workspace.atom.commands.add.core:close (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:307:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
  5x -1:50.1.0 core:backspace (atom-text-editor.editor.mini)
  2x -0:16.5.0 core:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "atom-monoindustrial"
    ],
    "disabledPackages": [
      "space-tab"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.0
atom-color-highlight, v3.0.8
atom-monoindustrial, v0.1.0
autocomplete-plus, v2.12.0
color-picker, v1.7.0
emmet, v2.3.8
language-blade, v0.12.0
language-ejs, v0.1.0
language-nginx, v0.5.1
language-smarty-php, v0.5.0
linter, v0.12.1
linter-jshint, v0.1.2
linter-php, v0.0.12
lorem-ipsum, v0.4.0
open-last-project, v0.4.1
recent-files, v0.3.0
travis-ci-status, v0.13.0

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
This should be fixed by https://github.com/AtomLinter/linter-php/commit/4f52e2ca452c18dedc15d01ffb9acdeed28d8964 which was released in `0.0.13`
