### ISSUE TITLE
Uncaught Error: spawn ENOMEM

### ISSUE THREAD

**Issue by uonick** [AtomLinter/linter-php#171]
[Enter steps to reproduce below:]

1. Open Atom
2. Go to any tab

**Atom Version**: 1.8.0
**System**: linux 4.4.0-24-generic
**Thrown From**: [linter-php](https://github.com/AtomLinter/linter-php) package, v1.2.0

### Stack Trace

Uncaught Error: spawn ENOMEM

```
At /usr/share/atom/resources/app.asar/src/buffered-process.js:262

Error: spawn ENOMEM
    at exports._errnoException (util.js:856:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:374:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/usr/share/atom/resources/app.asar/src/buffered-process.js:190:44)
    at new BufferedProcess (/usr/share/atom/resources/app.asar/src/buffered-process.js:52:14)
    at /home/user/.atom/packages/linter-php/node_modules/atom-linter/lib/helpers.js:58:77
    at Object.<anonymous> (/home/user/.atom/packages/linter-php/node_modules/atom-linter/lib/helpers.js:23:18)
    at [object Generator].next (native)
    at step (/home/user/.atom/packages/linter-php/node_modules/atom-linter/lib/helpers.js:114:191)
    at /home/user/.atom/packages/linter-php/node_modules/atom-linter/lib/helpers.js:114:368
```

### Commands

```
     -9:43.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -9:42 core:move-right (atom-text-editor.editor.is-focused)
  4x -9:41.7.0 core:select-right (atom-text-editor.editor.is-focused)
  3x -9:34.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:28.9.0 core:save (atom-text-editor.editor.is-focused)
     -4:05.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:12.3.0 core:delete (atom-text-editor.editor.is-focused)
     -0:09.6.0 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -0:09.6.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -0:08.6.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-java",
      "language-make",
      "language-objective-c",
      "language-perl",
      "language-sass",
      "language-shellscript",
      "language-toml",
      "open-on-github",
      "welcome",
      "language-python",
      "spell-check",
      "language-ruby",
      "language-ruby-on-rails",
      "archive-view",
      "deprecation-cop",
      "exception-reporting",
      "grammar-selector",
      "incompatible-packages",
      "language-go",
      "link",
      "styleguide",
      "timecop",
      "php-hyperclick",
      "minimap-bookmarks",
      "new-file-plus",
      "atom-autocomplete-php",
      "autocomplete-php",
      "language-volt",
      "php-class-tree"
    ],
    "packagesWithKeymapsDisabled": [],
    "projectHome": "/var/www/magento_test/",
    "themes": [
      "one-dark-ui",
      "dimmed-dark-ocean-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by uonick** [comment]
Nope

**Comment by Arcanemagus** [comment]
What OS are you on? It sounds like something is very wrong with it...

**Comment by Arcanemagus** [comment]
Also, silly question but you _have_ checked your memory usage, right?

**Comment by uonick** [comment]
System: linux 4.4.0-24-generic
16.04 Xenial Xerus - Ubuntu

Yes, I always have a free ~3 GB mem

**Comment by Arcanemagus** [comment]
Have you tried restarting?

**Comment by uonick** [comment]
Yes, the problem disappears for a while

**Comment by Arcanemagus** [comment]
Hmmm, I'm not really sure what further steps to take to troubleshoot your system if it keeps showing up. Something is obviously wrong though if it's claiming you are out of memory with ~3 GB free.

Marking this as closed for now since this isn't a problem with this package. If you have any other questions or if I have another idea I'll post here though.
