### ISSUE TITLE
Error: spawn php ENOENT when opening .php file

### ISSUE THREAD

**Issue by KK2345** [AtomLinter/linter-php#192]
When I open php file I get following error:

```
Error: spawn php ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
```

**Comment by Arcanemagus** [comment]
Do you have `php` installed on your system? Have you specified the full path to `php` in the settings?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
