### ISSUE TITLE
Error: PHP Warning: Module 'memcached' already loaded in Unknown on line 0

### ISSUE THREAD

**Issue by rzelnik** [AtomLinter/linter-php#216]
Each time I type any character in Atom with active linter-php, this error message is shown:

```
Error: PHP Warning:  Module 'memcached' already loaded in Unknown on line 0
    at ChildProcess.<anonymous> (/home/rzelnik/.atom/packages/linter-php/node_modules/sb-exec/lib/index.js:56:20)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
```

**Comment by Arcanemagus** [comment]
The `PHP Warning:  Module 'memcached' already loaded in Unknown on line 0` is coming direct from `php`'s `stderr`, I'm guessing you have the `memcached` module listed twice in your `php.ini`.

**Comment by rzelnik** [comment]
Oh, you are right, sorry for irrelevant bug report.

**Comment by Arcanemagus** [comment]
No worries 😉.
