### ISSUE TITLE
Error: spawn C:\xampp\php ENOENT     at getENOENTError

### ISSUE THREAD

**Issue by mmFooD** [AtomLinter/linter-php#225]
I get this error when saving a pdf. I have the php executable path as `C:\xampp\php`
I'm using xampp (php 7) and atom 1.12.6
```
C:\Users\{Username}\.atom\packages\linter-php\lib\main.js:41 Error: spawn C:\xampp\php ENOENT
    at getENOENTError (C:\Users\{Username}\.atom\packages\linter-php\node_modules\sb-exec\lib\helpers.js:159:15)
    at ChildProcess.<anonymous> (C:\Users\{Username}\.atom\packages\linter-php\node_modules\sb-exec\lib\index.js:50:46)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

**Comment by Arcanemagus** [comment]
Does it work if you put the `.exe` on the end?

Also your language packages in Atom seem to be rather screwed up if this package is running at all on PDF files.
