### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, uv_chdir

### ISSUE THREAD

**Issue by sijpkes** [AtomLinter/linter-php#249]
[Enter steps to reproduce:]

1. Re-opening Atom after computer being switched off for the weekend.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.2
**Thrown From**: [linter-php](https://github.com/AtomLinter/linter-php) package 1.3.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, uv_chdir

```
At /Users/ps158/.atom/packages/linter-php/node_modules/graceful-fs/polyfills.js:21

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at process.chdir (/packages/linter-php/node_modules/graceful-fs/polyfills.js:21:9)
    at lint (/packages/jshint/index.js:229:10)
    at complete (/packages/jshint/node_modules/lodash/index.js:7697:25)
    at delayed (/packages/jshint/node_modules/lodash/index.js:7707:11)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.23 
atom-html-preview 0.1.22 
atom-minify 0.8.0 
atom-ternjs 0.18.2 
atom-wrap-in-tag 0.6.0 
brunch-with-atom 0.2.3 
busy-signal 1.4.1 
color-picker 2.2.5 
declarations 1.1.3 
file-header 1.13.4 
fixmyjs 1.4.1 
git-plus 7.7.0 
intentions 1.1.2 
intentions-colorpicker 1.0.1 
jira-issue-search 1.0.3 
jshint 1.8.6 
jslint 1.5.1 
language-expressionengine 0.2.3 
linter 2.1.4 
linter-htmlhint 1.3.3 
linter-php 1.3.2 
linter-tidy 2.3.1 
linter-ui-default 1.2.3 
markdown-writer 2.6.4 
minimap-split-diff 0.3.7 
mylyn-for-atom 0.8.0 
node-debug 0.1.7 
php-class-tree 1.0.0 
php-debug 0.2.4 
remote-atom 1.3.10 
ruby-block 0.3.6 
split-diff 1.3.0 
symbols-tree-view 0.14.0 
uglify-html 2.0.0 
```

**Comment by Arcanemagus** [comment]
> `at lint (/packages/jshint/index.js:229:10)`

Looks like this is a bug in the [jshint](https://atom.io/packages/jshint) package, it just happens that Atom decided to use the `graceful-fs` module from this package so the stack trace got polluted over to here.

**Comment by sijpkes** [comment]
I've removed JSHint and am using the linter package only now. Problem solved.
