### ISSUE TITLE
Uncaught Error: Cannot find module 'atom-package-deps'

### ISSUE THREAD

**Issue by yyb568** [AtomLinter/linter-php#267]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.7 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [linter-php](https://github.com/AtomLinter/linter-php) package 1.4.0

### Stack Trace

Uncaught Error: Cannot find module 'atom-package-deps'

```
At module.js:472

Error: Cannot find module 'atom-package-deps'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.19.7/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.19.7/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.19.7/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.19.7/resources/app/src/native-compile-cache.js:66:33)
    at installLinterPhpDeps (/packages/linter-php/lib/main.js:29:9)
```

### Commands

```
     -0:22.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-simplified-chinese-menu 0.6.5 
file-icons 2.1.11 
goto 1.8.3 
goto-definition 1.3.4 
linter-php 1.4.0 
php-cs-fixer 4.1.1 
php-debug 0.2.5 
```

**Comment by Arcanemagus** [comment]
APM unfortunately sometimes fails to install all dependencies, please re-install the package.
