### ISSUE TITLE
Error running PHP Error: Process execution timed out - node_modules\sb-exec\lib\index.js:89:18

### ISSUE THREAD

**Issue by danielefavi** [AtomLinter/linter-php#274]
Hello,
I'm getting often the following error:

[Linter] Error running PHP Error: Process execution timed out
    at C:\Users\Daniele\.atom\packages\linter-php\node_modules\sb-exec\lib\index.js:89:18

I'm running Atom v1.21.1 on windows.
I don't know how to replicate this error because it appears randomly: sometimes when I change the tab or open a file.

Thank you a lot!

**Comment by Arcanemagus** [comment]
There isn't much that can be done here, there are some ways to work around this but they are only band-aids to the real problem that for some reason `php` is taking a _long_ time to parse your file.

You can disable linting on changes so it will only update results when the document is saved, which will greatly reduce the number of times this provider calls out to `php`.

As far as what can be done in this provider, a `uniqueKey` can be added to automatically kill previous runs of this provider when a new one is requested, although I've seen reports that this isn't working on some people's machines.

**Comment by zemiacsik** [comment]
After last Atom update I have started to encounter this. When I open a blank Atom and then re-open some project, it basically kills my pc for couple of minutes.

1. It starts with:
`VM22 <embedded>:14 FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory`

2. Then 14x variations of this:
<--- Last few GCs --->

[16268:0000023175F8ABD0]    11590 ms: Scavenge 40.3 (43.6) -> 39.6 (43.6) MB, 1.6 / 0.0 ms  allocation failure 
[16268:0000023175F8ABD0]    12019 ms: Scavenge 40.7 (44.1) -> 40.0 (44.6) MB, 1.2 / 0.0 ms  allocation failure 
[16268:0000023175F8ABD0]    12238 ms: Scavenge 41.0 (44.6) -> 40.3 (44.6) MB, 1.1 / 0.0 ms  allocation failure 
[16268:0000023175F8ABD0]    12262 ms: Scavenge 41.3 (44.6) -> 40.6 (44.6) MB, 2.6 / 0.0 ms  allocation failure 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000001EEAEE226A9 <JSObject>
    2: createContext(aka createContext) [vm.js:75] [bytecode=000003DFF7D69639 offset=38](this=0000026E4A802311 <undefined>,sandbox=0000022BE2FD06F9 <Object map = 00000022080AAEC9>)
    4: runInNewContext [vm.js:124] [bytecode=000003DFF7D693A9 offset=5](this=0000027A865A2269 <Object map = 0000027B2EAFA181>,code=0000022BE2FD06D1 <String[416]\: handle = function (match, expression, context) {\n  ...

3. Then 13x this:
`C:\Users\me\.atom\packages\linter\lib\linter-registry.js:155 [Linter] Error running PHP Error: Process execution timed out
    at C:\Users\me\.atom\packages\linter-php\node_modules\sb-exec\lib\index.js:89:18`

4. And finaly:
`VM22 <embedded>:11 Uncaught (in promise)`
Event ...
`srcElement : IDBRequest {result: undefined, error: DOMException: The transaction was aborted, so the request cannot be fulfilled., source: IDBObjectStore, transaction: IDBTransaction, readyState: "done", …}
target : IDBRequest {result: undefined, error: DOMException: The transaction was aborted, so the request cannot be fulfilled., source: IDBObjectStore, transaction: IDBTransaction, readyState: "done", …}`

**Comment by catscarlet** [comment]
Maybe a little tip to help.

I'm using Atom 1.57 on Linux Mint 20.2 with PHP 7.4.3, linter version 3.4.0 and linter-php 1.6.1. Also I'm suffering this issue for years

```
/home/cat/.atom/pack…ter/dist/index.js:1 [Linter] Error running PHP Error: Process execution timed out
    at /home/cat/.atom/pack…xec/lib/index.js:89
(anonymous)	@	/home/cat/.atom/pack…ter/dist/index.js:1
```

I got a little more trick:

![screenshot_by_flameshot_at_20210930163926](https://user-images.githubusercontent.com/10594035/135418290-b5277aa0-822c-4813-89f1-afef72ae53d2.png)




Uncheck `Lint Preview Tabs` can also reduce some PHP usage so to reduce the number of times.

**Comment by bcpeterson7** [comment]
catscarlet's trick above worked for me. Thank you.
