### ISSUE TITLE
Error started happening today? [Linter] Error running PHP Error: Line number (353) greater than maximum line (195)

### ISSUE THREAD

**Issue by IdrisDose** [AtomLinter/linter-php#284]
```
[Linter] Error running PHP Error: Line number (353) greater than maximum line (195)
    at Object.generateRange (<user>\.atom\packages\linter-php\node_modules\atom-linter\lib\index.js:162:11)
    at Object.<anonymous> (file:///<user>/.atom/packages/linter-php/lib/main.js:112:28)
    at Generator.next (<anonymous>)
    at step (<user>\.atom\packages\linter-php\lib\main.js:7:273)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

I've tried installing phpcs and reinstalling the linter-php plugin, changing PHP versions as well. Is there anything I can try?

**Comment by Arcanemagus** [comment]
Are you able to reliably reproduce this? If so are you able to share the file in the state that shows this message?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
