### ISSUE TITLE
error when php not in path (windows)

### ISSUE THREAD

**Issue by mdgeus** [AtomLinter/linter-php#52]
I have multiple PHP versions installed on my machine, therefor I don't have php.exe in the PATH.
I have added the location to php.exe in atom/config.cson but I still get errors.

  "linter-php":
    phpExecutablePath: "C:/PHP/php.exe"

Error: write EPIPE
  at exports._errnoException (util.js:734:11)
  at Socket._writeGeneric (net.js:668:26)
  at Socket._write (net.js:687:8)
  at doWrite (_stream_writable.js:295:12)
  at writeOrBuffer (_stream_writable.js:282:5)
  at Socket.Writable.write (_stream_writable.js:210:11)
  at Socket.write (net.js:612:40)
  at C:\Users\nl0360\.atom\packages\linter-php\node_modules\atom-linter\lib\helpers.coffee:34:30
  at Object.module.exports.Helpers._exec (C:\Users\nl0360\.atom\packages\linter-php\node_modules\atom-linter\lib\helpers.coffee:23:16)
  at Object.module.exports.Helpers.exec (C:\Users\nl0360\.atom\packages\linter-php\node_modules\atom-linter\lib\helpers.coffee:13:13)
  at Object.provider.lint (C:\Users\nl0360\.atom\packages\linter-php\lib\main.coffee:38:24)
  at C:\Users\nl0360\.atom\packages\linter\lib\editor-linter.coffee:69:26
  at currentLinter (C:\Users\nl0360\.atom\packages\linter\lib\editor-linter.coffee:68:20)
  at C:\Users\nl0360\.atom\packages\linter\lib\editor-linter.coffee:82:23
  at Set.forEach (native)
  at EditorLinter.triggerLinters (C:\Users\nl0360\.atom\packages\linter\lib\editor-linter.coffee:64:26)
  at C:\Users\nl0360\.atom\packages\linter\lib\editor-linter.coffee:57:27

**Comment by Arcanemagus** [comment]
The current version uses the (somewhat) standardized `executablePath` option, not the specific `phpExecutablePath` that previous versions did.

**Comment by mdgeus** [comment]
Yes,
"linter-php":
    executablePath: "C:/PHP/php.exe"
is working.

maybe you should update the settings manual page?

**Comment by Arcanemagus** [comment]
Readme is fixed, thanks for the report that it wasn't caught in the update :wink:.
