### ISSUE TITLE
Error: 'php' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Shmink** [AtomLinter/linter-php#60]
Error: 'php' is not recognized as an internal or external command,
operable program or batch file.
  at exit (C:\Users\Tommy\.atom\packages\linter-php\node_modules\atom-linter\lib\helpers.coffee:29:24)
  at triggerExitCallback (C:\Users\Tommy\AppData\Local\atom\app-1.0.5\resources\app.asar\src\buffered-process.js:213:47)
  at C:\Users\Tommy\AppData\Local\atom\app-1.0.5\resources\app.asar\src\buffered-process.js:227:18
  at Socket.<anonymous> (C:\Users\Tommy\AppData\Local\atom\app-1.0.5\resources\app.asar\src\buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

**AND**

Error: 'php' is not recognized as an internal or external command,
operable program or batch file.
  at exit (C:\Users\Tommy\.atom\packages\linter-php\node_modules\atom-linter\lib\helpers.coffee:29:24)
  at triggerExitCallback (C:\Users\Tommy\AppData\Local\atom\app-1.0.5\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\Tommy\AppData\Local\atom\app-1.0.5\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12

**Package number**
v 1.0.4

**Atom version**

v 1.0.5

**Comment by Project0** [comment]
You need to specify the path to your php binary in the settings while  php is not available through the PATH environment.

**Comment by steelbrain** [comment]
Closing based on  @Project0's comment.
