### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by benfeatherstone** [AtomLinter/linter-php#62]
[Enter steps to reproduce below:]

1. Open index.php
2. ...

**Atom Version**: 1.0.6
**System**: Ubuntu 15.04
**Thrown From**: [linter-php](https://github.com/AtomLinter/linter-php) package, v1.0.3

### Stack Trace

Uncaught Error: spawn EACCES

```
At /usr/share/atom/resources/app.asar/src/buffered-process.js:260

Error: spawn EACCES
    at exports._errnoException (util.js:734:11)
    at ChildProcess.spawn (child_process.js:1145:11)
    at Object.exports.spawn (child_process.js:977:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/usr/share/atom/resources/app.asar/src/buffered-process.js:188:44)
    at new BufferedProcess (/usr/share/atom/resources/app.asar/src/buffered-process.js:52:14)
    at /home/ben/.atom/packages/linter-php/node_modules/atom-linter/lib/helpers.coffee:100:28
    at Object.module.exports.Helpers._exec (/home/ben/.atom/packages/linter-php/node_modules/atom-linter/lib/helpers.coffee:57:14)
    at Object.module.exports.Helpers.exec (/home/ben/.atom/packages/linter-php/node_modules/atom-linter/lib/helpers.coffee:27:19)
    at Object.provider.lint (/home/ben/.atom/packages/linter-php/lib/main.coffee:43:28)
    at Promise.then._this.emitter.emit.linter (/home/ben/.atom/packages/linter/lib/linter-registry.coffee:97:31)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "linter-php": {
    "executablePath": "/opt/lampp/bin/"
  }
}
```

### Installed Packages

```coffee
# User
emmet, v2.3.12
linter, v1.3.4
linter-php, v1.0.3
minimap, v4.12.2
project-manager, v1.15.11
remote-sync, v3.1.2

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
If you are specifying the path to php yourself instead of letting the system grab it from $PATH you need to specify the _full_ path, not the folder.

In your case I'm assuming this would be `/opt/lampp/bin/php`

**Comment by benfeatherstone** [comment]
Thanks...it didn't set a $PATH variable when I installed XAMPP, but that fixed it. Thanks for the quick response

**Comment by Arcanemagus** [comment]
If that fixed it please mark the issue as closed :wink:. And enjoy!
