### ISSUE TITLE
Failed to load the linter-php package

### ISSUE THREAD

**Issue by StefanoMagrassi** [AtomLinter/linter-php#85]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Debian GNU/Linux
**Thrown From**: [linter-php](https://github.com/AtomLinter/linter-php) package, v1.1.0

### Stack Trace

Failed to load the linter-php package

```
At Error parsing /home/magrassi-nexxa/.atom/packages/linter-php/node_modules/atom-linter/node_modules/tmp/package.json: Unexpected end of input

SyntaxError: Error parsing /home/magrassi-nexxa/.atom/packages/linter-php/node_modules/atom-linter/node_modules/tmp/package.json: Unexpected end of input
    at Object.parse (native)
    at readPackage (module.js:77:52)
    at tryPackage (module.js:87:13)
    at Function.Module._findPath (module.js:155:20)
    at Module._resolveFilename (module.js:332:25)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/home/magrassi-nexxa/.atom/packages/linter-eslint/node_modules/atom-linter/lib/helpers.coffee:5:7)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "projectHome": "/home/magrassi-nexxa/dev",
    "disabledPackages": [
      "language-java",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-c",
      "language-go",
      "language-objective-c",
      "language-perl",
      "language-ruby",
      "language-ruby-on-rails",
      "language-toml"
    ]
  }
}
```

### Installed Packages

```coffee
# User
auto-detect-indentation, v0.4.2
autoclose-html, v0.19.0
docblockr, v0.7.3
file-icons, v1.6.11
highlight-line, v0.11.0
highlight-selected, v0.10.1
linter, v1.10.0
linter-csslint, v1.1.0
linter-eslint, v4.0.0
linter-jshint, v1.2.1
linter-jsonlint, v1.0.1
linter-less, v2.2.0
linter-php, v1.1.0
linter-tidy, v1.0.1
linter-xmllint, v0.0.7
open-recent, v4.0.1
project-manager, v2.6.5

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Looks like you didn't get a complete download of one of the module dependencies, try uninstalling/reinstalling it?

**Comment by StefanoMagrassi** [comment]
You're right! Now everything works.

Thank you
